title: Formazione Blue Reply
description: Esercizi per la formazione neo-assunti Blue Reply
plugins:
  - jekyll-remote-theme
remote_theme: pmarsceill/just-the-docs

# GitHub Pages settings
github:
  production: true

# Base URL (change if your site is hosted at a subpath)
baseurl: ""

# URL of your site
baseurl: "/training-blue-reply"
url: "https://crisz.github.io/training-blue-reply/"

# Navigation
just_the_docs:
  nav_position: left
