theme: jekyll-theme-minimal
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "FAQ"
    url: /faq/
  - title: "Contact"
    url: /contact/
title: Formazione Blue Reply
description: Esercizi per la formazione neo-assunti Blue Reply